### ISSUE TITLE
Failed Link

### ISSUE THREAD

**Issue by mohanr** [neomatrix369/adoptopenjdk-getting-started-kit#11]
I was looking for lambdas on Nashorn but this fails to link.
http://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/content/en/openjdk-projects/JavaScript_J2D.pdf

**Comment by neomatrix369** [comment]
Its fixed now  - http://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/content/en/openjdk-projects/nashorn.html, take a look.

It loads into github, but if you know of another better solution via gitbook, I'll be happy to fixed it for you, or you can send me a pull request.
